### ISSUE TITLE
Not picking up qbcore framework

### ISSUE THREAD

**Issue by jamesdeen717** [boofiboi/FiveM-Discord-Presence#3]
im getting an error in for es_extended when im on qbcore ran the old version worked fine

**Comment by boofiboi** [comment]
Delete [Line 2 in server.lua](https://github.com/boofiboi/FiveM-Discord-Presence/blob/ed040bcbbe99b6d8ac79104984c3386c14a28751/server/server.lua#L2)

**Comment by jamesdeen717** [comment]
![Screenshot 2024-06-20 154819](https://github.com/boofiboi/FiveM-Discord-Presence/assets/154687721/6f3bd366-430c-4a47-a1ef-fd24fdacbb73)
Still not working?

**Comment by boofiboi** [comment]
I think i know whats going on.

I'll fix it in the morning.

**Comment by boofiboi** [comment]
Fixed in [1.6](https://github.com/boofiboi/FiveM-Discord-Presence/releases/tag/1.6)
