### ISSUE TITLE
[BUG] Buttons & images

### ISSUE THREAD

**Issue by xDragon11x13** [boofiboi/FiveM-Discord-Presence#5]
**Describe the bug**
Buttons are not loaded

**Screenshots**

My Config

![Bild_2024-07-06_160135806](https://github.com/boofiboi/FiveM-Discord-Presence/assets/121519509/f592570f-c25e-4189-99a6-5decb3f97325)

My Application ID

![Bild_2024-07-06_160034670](https://github.com/boofiboi/FiveM-Discord-Presence/assets/121519509/f413ef3f-4c36-4be4-a4f4-76e89617e93e)

Rich Presence

![Bild_2024-07-06_160921794](https://github.com/boofiboi/FiveM-Discord-Presence/assets/121519509/b20ab021-6e8b-43cd-b0de-7f8ac9334f8c)

**Framework**
ESX 1.10.5

**Additional context**
My buttons are not loaded and not displayed

**Comment by boofiboi** [comment]
AFAIK this is FiveM and not this script, but i'll look into it.

**Comment by xDragon11x13** [comment]
Thank you very much ❤️

**Comment by boofiboi** [comment]
As I said, this is a FiveM issue, and there's nothing much I can do about this.

**Comment by boofiboi** [comment]
Okay, this wasn't a FiveM issue, it was a discord issue.

If you check by clicking on your profile, you will only see the text parts. Other people however do see the buttons.
![image](https://github.com/user-attachments/assets/7a65a08c-97cd-468d-a1a9-3bc0d222702d)

**Comment by xDragon11x13** [comment]
Thank you very much!
