### ISSUE TITLE
[BUG] Works but theres this error in the console

### ISSUE THREAD

**Issue by operationairstrike** [boofiboi/FiveM-Discord-Presence#7]
**Describe the bug**
[A clear and concise description of what the bug is.]
[script:discord] SCRIPT ERROR: @discord/server/server.lua:8: attempt to compare string with nil

**To Reproduce**
1. Run it
2. Look at server console

**Expected behavior**
No errors

**Framework**
ESX

**Additional context**
Thanks.

**Comment by boofiboi** [comment]
This seems to be harmless, your server just can't download the latest VERSION file from this repo for some reason.

**Comment by operationairstrike** [comment]
Thanks for your response. I like my console clean yk. How could I get rid of this error?

**Comment by boofiboi** [comment]
I'll add in error handling so it looks clean and neat.

**Comment by boofiboi** [comment]
[1.8](https://github.com/boofiboi/FiveM-Discord-Presence/releases/tag/1.8) should fix it.

**Comment by operationairstrike** [comment]
[script:discord] Error parsing script @discord/server/server.lua in resource discord: @discord/server/server.lua:18: <break> at line 10 not inside a loop (with v 1.8) @boofiboi

**Comment by boofiboi** [comment]
I installed GTA V again, ill get a FiveM server set up and fix this.

**Comment by operationairstrike** [comment]
Yo I recommend using the local server

**Comment by boofiboi** [comment]
I need to get a fiveM server running either way for my next script.

**Comment by boofiboi** [comment]
[Final fix?](https://github.com/boofiboi/FiveM-Discord-Presence/releases/tag/1.9)

**Comment by operationairstrike** [comment]
Ty bro I will try it later or like in 5 mins😂

**Comment by boofiboi** [comment]
I take its fixed, so I'll be closing the issue

**Comment by operationairstrike** [comment]
I haven't tested it yet, I will reopen if it doesn't work after testing. Thanks for the fixes.
