### ISSUE TITLE
[BUG] Error in console

### ISSUE THREAD

**Issue by operationairstrike** [boofiboi/FiveM-Discord-Presence#8]
Yo the 1.9 didnt fix it, now i get: [      script:discord] SCRIPT ERROR: @discord/server/server.lua:12: attempt to compare string with nil
[      script:discord] > userCallback (@discord/server/server.lua:12)

**Comment by boofiboi** [comment]
_do you even have VERSION in the script folder..._

**Comment by operationairstrike** [comment]
I have all files sir

**Comment by operationairstrike** [comment]
Do you want a screenshot 😂

**Comment by operationairstrike** [comment]
![grafik](https://github.com/user-attachments/assets/17a65d65-4aa8-4415-9bb3-ba9eb517a2b7)

**Comment by operationairstrike** [comment]
folder name is discord

**Comment by operationairstrike** [comment]
does it matter?

**Comment by boofiboi** [comment]
Yes it does. 
It needs to be "FiveM-Discord-Presence" or else [Line 7](https://github.com/boofiboi/FiveM-Discord-Presence/blob/f3e21cd64a23a09ce81bb38aea3e80b58e289870/server/server.lua#L7) returns nil and there's your issue.

**Comment by operationairstrike** [comment]
IM SO SORRY😭 where can I rename it so that it uses discord as resource name for the Version check? Is it bc the repository has this name?

**Comment by operationairstrike** [comment]
I'm really sorry. Thanks for the fixes tho. I will rename it on line 7, I guess?

**Comment by operationairstrike** [comment]
I was thinking about this yesterday, and i think it's true that it's 99% of the time the user that is too dumb to use it and not the code.😂💀

**Comment by operationairstrike** [comment]
Yo you may add a line to the readme so that people know.

**Comment by boofiboi** [comment]
It's not the user, its me.

I coded it with hardcoded variables.

**Comment by operationairstrike** [comment]
Fair point I thought about using $PATH somehow to automatically get the path it's in yk. That would be awesome tbh.

**Comment by operationairstrike** [comment]
I changed it and there's seems to be no error now

**Comment by operationairstrike** [comment]
I suggest using $PATH in the code
