### ISSUE TITLE
Error with script (not working) 

### ISSUE THREAD

**Issue by ERIK8978978Q** [boofiboi/FiveM-Discord-Presence#9]
![IMG_4512](https://github.com/user-attachments/assets/93890158-4bdd-473f-839e-022c062e884b)
And i dont know how to configure it! :))

**Comment by boofiboi** [comment]
The script needs to be in `FiveM-Discord-Presence`, not `FiveM-Discord-Presence-main`.

You downloaded the source code not the release.

**Comment by boofiboi** [comment]
Fixed.
